#! /usr/bin/env bash

set -euo pipefail

function usage() {
    cat <<EOF
Usage: make-recovery-drive /dev/partition
EOF
}

function check_continue() {
    read -r -p "do you still want to proceed? [yN]: " choice
    case "$choice" in
        y|Y|yes|YES);;
        *)
            echo "aborting"
            exit 1;;
    esac
}

function run() {
    echo "[DEBUG] >>> $*"
    "$@"
}

function partition_is_luks() {
    cryptsetup isLuks "$partition" && echo "y" || echo "n"
}

function partition_get_size() {
    local partition_size
    partition_size=$(blockdev --getsize64 "$partition")
    echo $(( partition_size / (1024*1024*1024) ))
}

function partition_format_luks() {
    run cryptsetup luksFormat "$partition"
}

function partition_format_ext4() {
    run mkfs.ext4 /dev/mapper/recovery
}

function partition_open() {
    run cryptsetup luksOpen "$partition" recovery
}

function partition_close() {
    run cryptsetup luksClose recovery
}

function partition_mount() {
    run mount /dev/mapper/recovery "$mountpoint"
}

function partition_umount() {
    run umount "$mountpoint"
}

function rsync_data() {
    run rsync --delete -avzL -e ssh --exclude "/lost+found" "data.nicuveo.fr:data/Recovery/*" "."
}


if [ $# -ne 1 ]; then
    usage
    exit 2
fi

export partition="$1"

if [ ! -e "$1" ] ; then
    echo "[FATAL] Unknown partition $1"
    exit 3
fi

if [ "$(id -u)" -ne 0 ]; then
    echo "[INFO] rerunning this script as root"
    sudo bash "$0" "$@"
    exit $?
fi

mountpoint="$(mktemp -d)"
export mountpoint
trap "rmdir \"$mountpoint\" &> /dev/null || true" EXIT

partition_size=$(partition_get_size)
if [ "$partition_size" -gt 30 ]; then
    echo "[WARN] $1 is bigger than expected (${partition_size}GB)"
    check_continue
fi

is_luks="$(partition_is_luks)"
if [[ $is_luks == "y" ]]; then
    echo "[INFO] already a luks partition"
    partition_open
    partition_mount
else
    echo "[INFO] setting up the partition"
    partition_format_luks
    partition_open
    partition_format_ext4
    partition_mount
    chmod a+rwx "$mountpoint"
fi

pushd "$mountpoint" &> /dev/null
export -f run
export -f rsync_data
su "$SUDO_USER" -c 'rsync_data'
popd &> /dev/null

partition_umount
partition_close

if [[ $is_luks == "y" ]]; then
    echo "[INFO] recovery drive updated"
else
    echo "[INFO] recovery drive created"
fi
