#! /usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/recovery/common.sh"

function usage() {
    cat <<EOF
Usage: umount-recovery-drive [folder=$HOME/Backup]
EOF
}


if [ $# -gt 1 ]; then
    usage
    exit 1
fi
export mountpoint="${1:-$HOME/Backup}"

run_as_root "$@"

partition_umount
partition_close
