#! /usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/recovery/common.sh"

function usage() {
    cat <<EOF
Usage: make-backup-drive /dev/partition
EOF
}

function rsync_data() {
    cmd rsync --delete -avzL -e ssh --exclude "/lost+found" "data.nicuveo.fr:data/*" "."
}

function estimate_data_size() {
    # estimate data size by looking at the number of bytes used on the partition.
    # between this and the 1.1 scaling factor, it means we slightly overestimate
    # the actual size of a full backup
    ssh -T data.nicuveo.fr "df data/ -B 1" | awk 'NR==2 {print int((1.1 * $3) / 1073741824) }'
}


if [ $# -ne 1 ]; then
    usage
    exit 1
fi
export partition="$1"

partition_check_exists
run_as_root "$@"
mountpoint_setup

label=$(partition_get_label)
if [[ -n "$label" ]]; then
    echo "[INFO] partition label: $label"
fi

export -f estimate_data_size
estimated_data_size=$(su "$SUDO_USER" -c 'estimate_data_size')
partition_size=$(partition_get_size)
if [[ $partition_size -lt $estimated_data_size ]]; then
    echo "[FATAL] $partition is not big enough to store backup: ${partition_size}GB < ${estimated_data_size}GB"
    exit 3
fi

is_luks="$(partition_is_luks)"
if [[ $is_luks == "y" ]]; then
    echo "[INFO] already a luks partition"
    partition_open
    partition_mount
else
    echo "[INFO] setting up the partition"
    partition_format_luks
    partition_open
    partition_format_ext4
    partition_mount
    chmod a+rwx "$mountpoint"
fi

pushd "$mountpoint" &> /dev/null
export -f cmd
export -f rsync_data
su "$SUDO_USER" -c 'rsync_data'
popd &> /dev/null

partition_umount
partition_close

if [[ $is_luks == "y" ]]; then
    echo "[INFO] backup drive updated"
else
    echo "[INFO] backup drive created"
fi
